name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-java@v3
       with:
         distribution: 'zulu'
         java-version: '19'
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
         flutter-version: '3.10.x'
     - run: flutter pub get
     - run: flutter format --set-exit-if-changed .
     - run: flutter analyze .
     - run: flutter build apk
     - uses: actions/upload-artifact@v3
       with:
        name: sb-detector-alpha-apk
        path: build/app/outputs/apk/release/app-release.apk
